[versions]
kotlin = "2.2.20"
typeflows = "0.29.0-beta"
version-catalog-update = "1.0.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
typeflows = { id = "io.typeflows", version.ref = "typeflows" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }

[libraries]
typeflows-github = { module = "io.typeflows:typeflows-github", version.ref = "typeflows" }
typeflows-github-marketplace = { module = "io.typeflows:typeflows-github-marketplace", version.ref = "typeflows" }
